### ISSUE TITLE
`serverless invoke local` not supported

### ISSUE THREAD

**Issue by Buthrakaur** [awwong1/serverless-simple-parcel#2]
Hello,
I just tried this plugin for AWS Lambda development, but it looks like it doesn't handle `serverless invoke local -f myFunc -l` command. I tried to simply add `'before:invoke:local:invoke': this.bundle` to the `handlers` collection to be able to get it working and submit a PR, but it didn't help:

```
Serverless: Bundled xxx\.build\src\dist\handler.js
Serverless: Done bundling all parcel entries!
xxx\handler.js:1
(function (exports, require, module, __filename, __dirname) { export async function myFunc(event, context) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

Could you please take a look into this? I'm also confused by the configuration in `serverless.yml` file - is there any sample how to setup `entries` for a typical lambda project consisting of multiple *.js src files and some tests? Am I supposed to add all the JS files one by one to the entries or is there any wildcard support?

**Comment by awwong1** [comment]
I'll take a look as to why the local invoke handler did not work for you.

Your `serverless.yml` assumption is correct: you have to define each bundle one by one in the `entries` array. Mine looks something like this:

```yml
custom:
  envSensitive:
    development:
      watch: true
      minify: false
    production:
      watch: false
      minify: true
  parcel:
    options:
      minify: ${self:custom.envSensitive.${env:NODE_ENV}.minify, 'false'}
      watch: ${self:custom.envSensitive.${env:NODE_ENV}.watch, 'false'}
    entries:
      - watch: false
        file: src/hooks/cognito.ts
        outDir: dist
        target: node
        bundleNodeModules: true
      - file: src/ssr.ts
        outDir: dist
        outFile: handler.js
        target: node
        bundleNodeModules: true
      - file: src/public/index.html
        outDir: dist/src/public
        target: browser
```

The original project https://github.com/johnagan/serverless-parcel automatically bundles your lambda functions, but I'm not sure if it supports invoking local functions.
